from python_func import *
from loop_func import *


helloYou('Sarah')
helloYouLen('Sarah')
madLib()
dayOfTheWeek()
workOrSleepIn()
temperature()
tipCalculator()
tipCalculator2()
print1to10()
coins()
guess()
# =====list exercise=====
maxList()
minList()
even()
positive()
newListPositiveNo()
multiplyNum()
multiplyVector()
matrixAddition()
deDup()
# =====loop exercise=====
print1to10()
ntom()
printOddNum()
printSquare(5)
printSquareNtimes()
printBox()
printATriangle()
printATriangleNheight()
multiplicationTable()
printBanner()
triangleNumber()
fuctorNumber()
# ========string exercise=====
changeToUpperCase()
changeToCapitalizing()
reverseLetters()
leetspeak()
longlongVowles()
caesarCipher()
